sudo: false
language: python
cache: pip
python:
  - "3.6"
addons:
  apt:
    packages:
    - lftp
deploy:
  skip_cleanup: true
  provider: script
  script: curl -Ss https://raw.githubusercontent.com/OpenDataServices/opendataservices-deploy/master/open-contracting-profile-deploy.sh | bash -
  on:
    all_branches: true
script:
  - make
